// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWFF2iSRTjeYVPM4aBapHni5t1EfiNO30',
    appId: '1:705507248310:web:06eb8a5a4ddeefd8b7be17',
    messagingSenderId: '705507248310',
    projectId: 'my-fit-log-app',
    authDomain: 'my-fit-log-app.firebaseapp.com',
    storageBucket: 'my-fit-log-app.appspot.com',
    measurementId: 'G-QJNTEY54HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt48ROlcqE9Jnrsv5P9KZvDfI8a9dMkLo',
    appId: '1:705507248310:android:c2f025e903086de7b7be17',
    messagingSenderId: '705507248310',
    projectId: 'my-fit-log-app',
    storageBucket: 'my-fit-log-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFbeO3u7iH2Yqmk9LEPFkQPBqjtNaSBIs',
    appId: '1:705507248310:ios:963a189a46d75f94b7be17',
    messagingSenderId: '705507248310',
    projectId: 'my-fit-log-app',
    storageBucket: 'my-fit-log-app.appspot.com',
    iosClientId: '705507248310-gbn6cmg5bh751pbvsv6hokgel5auh72c.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFitLogApp',
  );
}
